name: CI_staging

on: workflow_call


jobs:
  deploy_staging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Setup Python 
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install Dependencies
        run: |
          echo Installing dependencies...
          python -m pip install --index-url ${PIP_INDEX_URL} --requirement requirements-test.txt
      - name: Package 
        run: |
          python setup.py bdist_wheel bdist_egg egg_info --tag-build rc${IRONFORGE_PULL_REQUEST}.post${IRONFORGE_COMMIT_COUNT}
      - name: Publish
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
          run: python -m twine upload --disable-progress-bar dist/*
      - name: bump version
        run: |
          bump2version minor --no-commit
  create_pr:
      needs: deploy_staging
      runs-on: ubuntu-latest
      steps:
        - uses: devops-infra/action-pull-request@v0.5.0
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            source_branch: 'master'
            target_branch: 'production'
            title: f"Staging changes for ${{ github.event.pull_request.number }}"
            body: f"Auto-generated request to stage the changes made to `master` branch as a result of merging ${{ github.event.pull_request.number }}"
