name: Flake8 Lint

on:
  # Triggers the workflow on push or pull request events to 'prod'
  pull_request:
    branches: [ "production" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This job is called "build"
  build:
    # Github creates a ubuntu image to checkout repo, compile, package.
    runs-on: ubuntu-latest
    env:
      PR_NUMBER: ${{ github.event.pull_request.number }}
      BASE_SHA: ${{ github.event.pull_request.base.sha }}
      PIP_INDEX_URL: https://artifactory.eng.nimblestorage.com/artifactory/api/pypi/pypi/simple
    # Tasks that will be executed as part of the job "build"
    name: Lint
    steps:
      - name: Check out source repository
        uses: actions/checkout@v2
      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: flake8 Lint
        uses: py-actions/flake8@v2
        with:
          ignore: "E203, E501"
          exclude: ".tox,
                    .git,
                    __pycache__,
                    docs/source/conf.py,
                    build,
                    dist,
                    tests/fixtures/*,
                    *.pyc,
                    *.egg-info,
                    .cache,
                    .eggs
                    lib/borg/cmd/driver/cli/fcinfo.py:E741,E743
                    lib/borg/cmd/driver/pyscsi/iscsi_encoder.py:E741
                    lib/borg/app/pyscsi/iscsi_encoder.py:E741
                    *.pyi: E301, E302, E305, E501, E701, E741, F401, F403, F405, F822"
          max-line-length: "120"
          path: "src"
          plugins: "flake8-bugbear==22.1.11 flake8-black"
